# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-01 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
