# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-05 16:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('presentations', '0002_auto_20180101_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 1, 5, 16, 26, 33, 942064, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
