# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-05 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentations', '0003_postmodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
