# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-05 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentations', '0004_auto_20180105_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
